version: 2.1

orbs:
  python: circleci/python@0.2.1

executors:
  tox-docker:
    docker:
      - image: themattrix/tox

jobs:
  build-and-test:
    executor: tox-docker
    steps:
      - checkout
      - run:
          command: tox
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
